sudo: false
language: node_js
node_js: stable
addons:
  chrome: stable
cache:
  yarn: true
install:
- |
    yarn install
script:
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
branches:
  only:
    - master
#env:
#  global:
#    - secure: ".... encrypted data ...."
